### ISSUE TITLE
AWS EBS Snapshot logic

### ISSUE THREAD

**Issue by atward** [Percona-Lab/mongodb_consistent_backup#220] opened 2017-09-15 03:29 UTC
I have used a large chunk of the current logic to implement backups using AWS EC2/EBS block level snapshots and am releasing it under the existing Apache Licence.

I'm just raising this issue as an FYI in case it is useful for development/adaptation or inclusion in future releases.
Documentation can be found [here](https://github.com/atward/aws-snapshot/blob/master/README.mongodb.md) with AWS specific logic in pl_mongo.Backup.AwsSnapshot

**Comment by timvaillancourt** [comment] 2018-02-22 22:45
Duplicate of #19. Please see this issue for updates.

**Closed by timvaillancourt** 2018-02-22 22:45 UTC
Labels: duplicate, enhancement
